### ISSUE TITLE
User Story: Edit a project

### ISSUE THREAD

**Issue by Robbie-Smith** [Robbie-Smith/kickstarter_clone#14]
As an authenticated user
When I visit the projects page
And I click on Edit Project
And I update that project's info
And I click on Update
I should be redirected to that project's show page
And my changes should be reflected

**Comment by drod1000** [comment]
As an authenticated user
When I visit the projects page
And I click on Edit Project
And I update that project's info
And I click on Update
I should be redirected to that project's show page
And my changes should be reflected

**Comment by Robbie-Smith** [comment]
@drod1000 @Dpalazzari if this is closed, can either of you mark it as closed?
