### ISSUE TITLE
Wireframes

### ISSUE THREAD

**Issue by Robbie-Smith** [Robbie-Smith/kickstarter_clone#7]
* Splash page (root)
* Project show
* Project index
* Project create
* Project edit
* Project support(give money to project)
* Login
* Sign-up
* Footer
* Navbar
* User dashboard

**Comment by Dpalazzari** [comment]
![project show - mobile](https://cloud.githubusercontent.com/assets/19585280/22676569/693476d6-eca9-11e6-8a29-4a05698a31ad.png)

**Comment by Robbie-Smith** [comment]
Looks great!

**Comment by case-eee** [comment]
@Dpalazzari looks awesome 👍
